theme: jekyll-theme-slate

title: Z-Kitty Launcher
description: "Terminal Session Manager for the Kitty Emulator - Intelligent Build Scripts & Desktop Integration"
show_downloads: true
github:
  repository_url: https://github.com/pilakkat1964/z-kitty-launcher

plugins:
  - jekyll-feed

markdown: kramdown
