baseurl: /z-kitty-launcher
theme: jekyll-theme-architect
title: Kitty Launcher
description: "Terminal session manager for Kitty emulator \u2014 launch and manage\
  \ terminal sessions from system tray"
show_downloads: true
github:
  repository_url: https://github.com/pilakkat1964/z-kitty-launcher
  owner_name: pilakkat1964
  owner_url: https://github.com/pilakkat1964
plugins:
- jekyll-feed
- jekyll-relative-links
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title/
defaults:
- scope:
    path: ''
  values:
    layout: default
relative_links:
  collections: true
keep_files:
- .git
- .github
exclude:
- Makefile
- .gitignore
- .github
- README.md
- Cargo.toml
- Cargo.lock
- src
- target
- scripts
parent_url: /z-tools
hierarchy_level: 2
hierarchy_parent_title: Z-Tools Portfolio

